### ISSUE TITLE
Use new encrypted-exclusive filter group

### ISSUE THREAD

**Issue by AetherUnbound** [spdconvos/encryptedbot_py#24]
This new radio filter group has been added which will only stream encrypted calls. We should switch the bot to it: https://openmhz.com/system/kcers1b?filter-type=group&filter-code=5efd784760e5840025aebad8

**Comment by spdconvos** [comment]
I like keeping the modularity of using specific talk group IDs. If SPD or other law enforcement agencies being monitored change which talk groups are encrypted or add new channels I would prefer to update our list instead of waiting for the OpenMHZ group to get updated.

Might be worth moving the config out of the python file though
